[package]
name = "sanctions-list-transform"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
quick-xml = { version = "0.39.0", features = ["serialize"] }
serde = { version = "1.0.228", features = ["derive"] }
